version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: develop
    restart: always
    networks:
      - develop
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
networks:
  develop:
